### ISSUE TITLE
No way to disable version checking

### ISSUE THREAD

**Issue by jamesjimmy88** [coolsimulations/EffectsLeft#3]
As per title. The mod also appears to ignore the _versionCheck_ setting in the _fml.toml_ config file.
Tested with EffectsLeft-1.18.1-0.1.0 on Forge 40.1.27.

**Comment by coolsimulations** [comment]
Thanks for the feedback. I intentionally decided not to add an entire config just for the update checker due to how rarely I plan to update this mod and keep the mod lightweight. If I ever need a config for this mod I'll add an option to disable this.
